version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  gateway-service:
    build: ./gateway-service/
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
